<a href="https://colab.research.google.com/github/Zaminur151/Deep-Learning-repo/blob/main/perceptron/01_perceptron_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

In [ ]:
# data= pd.read_csv('placement.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'placement.csv'

In [ ]:
!pip install -q kagglehub

In [ ]:
import kagglehub

path = kagglehub.dataset_download("ishanjha100/student-passfail-data")

print("Dataset path:", path)

Downloading to /root/.cache/kagglehub/datasets/ishanjha100/student-passfail-data/1.archive...

100%|██████████| 930/930 [00:00<00:00, 779kB/s]

Extracting files...
Dataset path: /root/.cache/kagglehub/datasets/ishanjha100/student-passfail-data/versions/1

In [ ]:
import os

print(os.listdir(path))

['Pass-Fail Data.csv']

In [ ]:
import pandas as pd

df = pd.read_csv(path + "/Pass-Fail Data.csv")

df.head(20)

,student_id,attendance_pct,homework_pct,midterm_score,study_hours_per_week,pass
0,1,95,92,88,12,1
1,2,88,85,79,10,1
2,3,60,55,58,4,0
3,4,72,70,65,6,1
4,5,40,45,50,3,0
5,6,85,90,91,14,1
6,7,78,80,74,8,1
7,8,55,60,62,5,0
8,9,90,88,84,11,1
9,10,68,65,60,6,1
10,11,30,35,42,2,0
11,12,82,78,76,9,1
12,13,74,70,68,7,1
13,14,50,48,55,4,0
14,15,92,95,93,15,1
15,16,65,60,59,5,0
16,17,80,85,82,10,1
17,18,45,50,52,3,0
18,19,88,90,86,12,1
19,20,70,68,66,7,1

In [ ]:
df['pass'].value_counts()

pass
1    60
0    40
Name: count, dtype: int64

In [ ]:
X = df[['student_id', 'attendance_pct', 'homework_pct', 'midterm_score','study_hours_per_week']]
y = df['pass']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (80, 5)
Testing data: (20, 5)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import Perceptron

model = Perceptron(
    max_iter=1000,
    eta0=0.1,
    random_state=42
)

In [ ]:
model.fit(X_train_scaled, y_train)

Perceptron(eta0=0.1, random_state=42)

In [ ]:
y_pred = model.predict(X_test_scaled)

print("Predicted:", y_pred)
print("Actual:   ", y_test.to_numpy())

Predicted: [1 1 1 1 0 0 0 1 0 0 0 1 0 1 0 1 1 1 1 1]
Actual:    [1 1 1 1 0 0 0 1 0 0 0 1 0 1 0 1 1 1 1 1]

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy percentage:", accuracy * 100, "%")

Accuracy: 1.0
Accuracy percentage: 100.0 %